#!/bin/bash

cat << EOF
.\" Manpage for _printf
.\"
.TH man 1 "30 Mar 2024" "1.0" "Printf Manual"
.SH NAME
_printf \- Print formatted output
.SH SYNOPSIS
.B _printf
[\fIformat\fR]
.SH DESCRIPTION
This manual page documents the usage of the \fI_printf\fR function, which is used to print formatted output similar to the standard C library function printf().
.PP
The \fI_printf\fR function takes a format string as input, which can contain conversion specifiers such as %c, %s, %d, %i, and %%.
.SH OPTIONS
.TP
\fBformat\fR
The format string containing conversion specifiers and optional arguments.
.SH RETURN VALUE
The function returns the number of characters printed.
.SH EXAMPLES
Print a string:
.nf
.B _printf "Hello, world!\n"
.fi
Print a formatted integer:
.nf
.B _printf "The answer is %d\n" 42
.fi
.SH SEE ALSO
.BR printf (3)
.SH AUTHOR
This manual page was written by Kamal and Samir KamalAbdullayev0 and samiribrh
EOF

